const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

const service = read('src/shared/services/CommentReactionService.js');
const bar = read('src/shared/components/CommentReactionBar.js');
const commentsCss = read('src/shared/styles/comments.css');
const adminService = read('src/shared/services/AdminService.js');
const firebaseManager = read('src/shared/firestore.js');
const adminHtml = read('src/pages/admin/admin.html');
const adminJs = read('src/pages/admin/admin.js');
const rules = read('rules/firestore.rules');
const storageRules = read('rules/storage.rules');
const firebaseConfig = read('firebase.json');
const functions = read('functions/index.js');
const movieDetails = read('src/pages/movie-details/movie-details.js');
const search = read('src/pages/search/search.js');

assert.ok(service.includes("const COMMENT_REACTION_CONFIG_COLLECTION = 'settings';"));
assert.ok(service.includes("const COMMENT_REACTION_CONFIG_ID = 'commentReactions';"));
assert.ok(service.includes('MAX_REACTION_CATALOG_SIZE = 24'));
assert.ok(service.includes('MAX_REACTION_ASSET_SIZE = 256 * 1024'));
assert.ok(service.includes("renderType: 'image'"));
assert.ok(service.includes('normalizeReactionImageUrl'));
assert.ok(service.includes('async loadConfig(force = false)'));
assert.ok(service.includes('subscribeToConfig(onChange)'));
assert.ok(service.includes('reactionTypes: config.reactions.map(({ id }) => id)'));
assert.ok(service.includes('async saveConfig(reactions, updatedBy = \'\')'));
assert.ok(bar.includes('const FALLBACK_REACTION_TYPES = ['));
assert.ok(bar.includes('reactionBarEscapeHtml(meta?.emoji || \'\')'));
assert.ok(bar.includes('function renderReactionButton(type, count, isActive, className, showCount = true)'));
assert.ok(bar.includes("'comment-reaction-picker-btn',\n                            false"));
assert.ok(bar.includes('static positionPicker(bar, picker, trigger)'));
assert.ok(bar.includes('static bindPickerPositioning(bar, picker, trigger)'));
assert.ok(commentsCss.includes('position: absolute;'));
assert.ok(commentsCss.includes('.comment-reaction-picker[data-placement="above"]'));
assert.ok(commentsCss.includes('bottom: calc(100% + 8px);'));
assert.ok(commentsCss.includes('.comment-reaction-btn.is-active {\n    border-color: transparent;'));
assert.ok(commentsCss.includes('.comment-reaction-picker-btn.is-active {\n    border-color: transparent;'));
assert.ok(commentsCss.includes('.comment-reaction-emoji {\n    font-size: 15.75px;'));
assert.ok(commentsCss.includes('.comment-reaction-visual {\n    display: inline-grid;'));
assert.ok(commentsCss.includes('border-radius: 4px;\n    line-height: 1;\n    overflow: hidden;'));
assert.ok(commentsCss.includes('.comment-reaction-image {\n    display: block;\n    max-width: 100%;\n    max-height: 100%;'));
assert.ok(adminService.includes('async getCommentReactionConfig(force = false)'));
assert.ok(adminService.includes('async saveCommentReactionConfig(reactions, currentAdminId)'));
assert.ok(adminService.includes('async uploadCommentReactionAsset(file, reactionId, currentAdminId)'));
assert.ok(firebaseManager.includes('async uploadCommentReactionAsset(file, reactionId)'));
assert.ok(firebaseManager.includes('async deleteCommentReactionAsset(storagePath)'));
assert.ok(adminHtml.includes('data-target="reaction-settings"'));
assert.ok(adminHtml.includes('id="commentReactionForm"'));
assert.ok(adminHtml.includes('id="commentReactionList"'));
assert.ok(adminHtml.includes('id="commentReactionEmojiInput"'));
assert.ok(adminHtml.includes('id="commentReactionLabelInput"'));
assert.ok(adminHtml.includes('id="commentReactionAssetInput"'));
assert.ok(adminHtml.includes('id="commentReactionAssetDropzone"'));
const reactionScriptIndex = adminHtml.indexOf('/src/shared/services/CommentReactionService.js');
const firestoreScriptIndex = adminHtml.indexOf('/src/shared/firestore.js');
assert.ok(reactionScriptIndex >= 0 && reactionScriptIndex < firestoreScriptIndex);
assert.ok(adminJs.includes('async loadCommentReactionConfig(force = false)'));
assert.ok(adminJs.includes('handleCommentReactionSubmit(event)'));
assert.ok(adminJs.includes('handleCommentReactionDelete(reactionId)'));
assert.ok(adminJs.includes('validateCommentReactionAsset(file)'));
assert.ok(adminJs.includes('previewCommentReactionAsset(file)'));
assert.ok(adminJs.includes('handleCommentReactionAssetPaste(event)'));
assert.ok(adminJs.includes('handleCommentReactionAssetDrop(event)'));
assert.ok(adminJs.includes("commentReactionForm.addEventListener('paste'"));
assert.ok(adminJs.includes('DataTransfer'));
assert.ok(adminJs.includes('saveCommentReactionConfig('));
assert.ok(rules.includes("match /settings/{settingId}"));
assert.ok(rules.includes('commentReactionAllowedTypes()'));
assert.ok(rules.includes("allow read: if settingId == 'commentReactions';"));
assert.ok(rules.includes('request.resource.data.reactionTypes.size()'));
assert.ok(storageRules.includes('match /comment_reaction_assets/{assetName}'));
assert.ok(storageRules.includes("request.resource.contentType in ['image/png', 'image/webp', 'image/gif']"));
assert.ok(firebaseConfig.includes('"storage":'));
assert.ok(functions.includes('async function getActiveCommentReactionTypes()'));
assert.ok(functions.includes('const counts = Object.fromEntries(activeReactionTypes.map((type) => [type, 0]));'));
assert.ok(movieDetails.includes('await reactionService.loadConfig?.();'));
assert.ok(movieDetails.includes('reactionService.subscribeToConfig?.'));
assert.ok(search.includes('await reactionService.loadConfig?.();'));
assert.ok(search.includes('reactionService.subscribeToConfig?.'));

console.log('commentReactionConfig.test.js: all tests passed');
