import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const service = fs.readFileSync(path.join(root, 'src/shared/services/RandomMarathonService.js'), 'utf8');
const page = fs.readFileSync(path.join(root, 'src/pages/random/random.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'src/pages/random/random.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'src/pages/random/random.css'), 'utf8');
const rules = fs.readFileSync(path.join(root, 'rules/firestore.rules'), 'utf8');
const functions = fs.readFileSync(path.join(root, 'functions/randomMarathon.js'), 'utf8');
const functionsIndex = fs.readFileSync(path.join(root, 'functions/index.js'), 'utf8');

assert.match(service, /maxMoviesPerUser\(\)\s*\{\s*return 3;/);
assert.match(service, /resolveCurrent\(resolution = 'watched', expectedRoundId = null, expectedItemId = null\)/);
assert.match(service, /expectedRoundId/);
assert.match(service, /expectedItemId/);
assert.match(service, /mutationUrl/);
assert.match(service, /_callMutation\('add'/);
assert.match(service, /latestRound !== roundForSubscription/);
assert.match(page, /_marathonAuthRefreshId/);
assert.match(page, /const isAdmin = await this\.marathonService\.isAdmin\(\)\.catch\(\(\) => false\)/);
assert.match(page, /if \(refreshId !== this\._marathonAuthRefreshId\) return;/);
assert.doesNotMatch(service, /item\.data\(\)/);
assert.match(service, /Utils\.getDisplayName\(profile, fallbackUser\)/);
assert.match(service, /_decorateItems\(items\)/);
assert.match(service, /profileByUserId\.get\(item\.addedBy\)/);
assert.match(service, /let active = true/);
assert.match(service, /generation \+= 1/);
assert.match(service, /cached\.expiresAt > Date\.now\(\)/);
assert.match(page, /data-marathon-action="roll"/);
assert.match(page, /const nextState = await action\(\)/);
assert.match(page, /_refreshPoolModalIfOpen\(\)/);
assert.match(page, /Number\(marathonItem\.kpId\) === Number\(m\.kpId\)/);
assert.match(page, /author\.className = 'marathon-item-author'/);
assert.match(page, /item\.addedByName \|\| item\.addedBy/);
assert.match(page, /this\.marathonIsAdmin \|\| ownCount < RandomMarathonService\.maxMoviesPerUser/);
assert.match(page, /data-marathon-action="removed"/);
assert.match(page, /resolveCurrent\('watched', expectedRoundId, expectedItemId\)/);
assert.match(page, /event\.target\.closest\?\.\('button'\)/);
assert.match(page, /_marathonPendingRemovals = new Set/);
assert.match(page, /this\._marathonPendingRemovals\.add\(item\.id\)/);
assert.match(page, /this\._marathonPendingRemovals\.has\(item\.id\)/);
assert.match(page, /this\._marathonPendingRemovals\.add\(item\.id\);\s*this\._renderMarathon\(\);\s*await this\._runMarathonAction/);
assert.match(page, /pool-list-item-marathon-add/);
assert.match(page, /class="pool-list-item-actions"/);
assert.match(page, /row\.className = 'pool-list-item marathon-list-item'/);
assert.match(page, /rowActions\.className = 'marathon-item-actions'/);
assert.match(css, /\.pool-list-item\s*\{[\s\S]*display:\s*grid/);
assert.match(css, /grid-template-columns:\s*36px\s+minmax\(0,\s*1fr\)\s+auto/);
assert.match(css, /\.pool-list-item-actions\s*\{/);
assert.match(css, /\.marathon-list-item\s*\{/);
assert.match(css, /\.marathon-item-actions\s*\{/);
assert.match(css, /\.pool-list-item-bonus \.chance-tag\s*\{[\s\S]*margin-left:\s*0/);
assert.match(html, /id="showMarathonBtn"/);
assert.match(html, /id="marathonSearchInput"/);
assert.match(html, /shared\/services\/RandomMarathonService\.js/);
assert.match(rules, /match \/randomMarathons\/current/);
assert.match(rules, /allow create, update, delete: if false;/);
assert.match(functions, /MAX_MOVIES_PER_USER = 3/);
assert.match(functions, /participantCounts/);
assert.match(functions, /createRandomMarathonHandler/);
assert.match(functions, /normalizeMovie/);
assert.match(functions, /round\.status !== "collecting"/);
assert.match(functions, /Math\.random\(\) \* queued\.length/);
assert.match(functions, /ownCount >= MAX_MOVIES_PER_USER/);
assert.match(functions, /INVALID_ITEM/);
assert.match(functions, /CURRENT_MOVIE_STALE/);
assert.match(functions, /expectedRoundId/);
assert.match(functions, /expectedItemId/);
assert.match(functions, /AUTH_REQUIRED/);
assert.match(functions, /readTransactionItems\(transaction, itemsRef\.where\("roundId", "==", round\.roundId\)\)/);
assert.doesNotMatch(functions, /getRoundItemDocs/);
assert.match(functionsIndex, /exports\.randomMarathon = onRequest/);

console.log('Random marathon contract passed.');
