const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const read = relative => fs.readFileSync(path.join(__dirname, '..', relative), 'utf8');
const service = read('src/shared/services/SeriesEpisodeRatingService.js');
const details = read('src/pages/movie-details/movie-details.js');
const detailsHtml = read('src/pages/movie-details/movie-details.html');
const detailsCss = read('src/pages/movie-details/movie-details.css');
const rules = read('rules/firestore.rules');
assert.match(rules, /match \/seriesEpisodeStats\/{movieId}\s*\{\s*allow read: if true;\s*allow write: if false;/);
const tmdb = read('src/shared/services/TMDBService.js');
const card = read('src/shared/components/MovieCard.js');
const ratings = read('src/pages/ratings/ratings.js');

assert.match(service, /collection = 'seriesEpisodeRatings'/);
assert.match(service, /return uid \+ '_' \+ kpId/);
assert.match(service, /return season \+ ':' \+ episode/);
assert.match(service, /_enqueueSeries\(userId, movieId/);
assert.match(service, /runTransaction\(async transaction/);
assert.doesNotMatch(service, /ratingSource|episodeAverage|manualBackup|ratingSum|ratedCount|calculateAggregate/);
assert.doesNotMatch(service, /getRatingService|invalidateAverageRatingsCache|invalidateRatingsCache|recalculateUserTopGenres|cacheMovie/);
assert.doesNotMatch(service, /getWatchlistService|removeFromWatchlist/);

assert.match(rules, /match \/seriesEpisodeRatings\/{seriesRatingId}/);
assert.match(rules, /allow list: if false/);
assert.match(rules, /hasOwnSeriesEpisodeRatingId/);
assert.match(rules, /episodes\.size\(\) <= 3000/);
assert.match(rules, /episodes\.size\(\) >= 1/);
assert.match(rules, /changedEpisodes\.size\(\) <= 1/);
assert.match(rules, /changedEpisodes\.hasOnly\(\[request\.resource\.data\.lastKey\]\)/);
const episodeValidation = rules.slice(rules.indexOf('    function isValidSeriesEpisodeRatingData('), rules.indexOf('    function hasOneValidEpisodeRatingChange('));
assert.match(episodeValidation, /hasOnly\(\[\s*'userId', 'movieId', 'tmdbId', 'episodes', 'lastKey', 'updatedAt'\s*\]\)/);
assert.doesNotMatch(episodeValidation, /ratingSum|ratedCount|mode|manualBackup/);
assert.match(rules, /request\.resource\.data\.episodes\.size\(\) == 1/);
assert.match(rules, /request\.resource\.data\.episodes\.diff\(resource\.data\.episodes\)\.affectedKeys\(\)/);
assert.match(rules, /\^\[0-9\]\{1,3\}:\[0-9\]\{1,5\}\$/);
assert.match(rules, /ratingSource in \['episodes', 'manual'\]/);
assert.match(rules, /episodeAverage is number/);
assert.match(rules, /episodesRatedCount is int/);
assert.doesNotMatch(rules, /ratingSource == 'episodes'/);
const episodeRules = rules.slice(rules.indexOf('    match /seriesEpisodeRatings/'), rules.indexOf('    match /commentReactions/'));
assert.match(episodeRules, /request\.resource\.data\.userId == resource\.data\.userId/);
assert.match(episodeRules, /request\.resource\.data\.movieId == resource\.data\.movieId/);
assert.doesNotMatch(episodeRules, /request\.resource\.data\.diff\(resource\.data\)/,
    'legacy aggregate fields can be removed during a full document replacement');

assert.match(details, /&& Number\.isInteger\(Number\(movie\?\.kinopoiskId\)\)/);
assert.match(details, /&& Number\.isInteger\(Number\(movie\?\.tmdbId \|\| movie\?\.externalId\?\.tmdb\)\)/);
assert.match(details, /isEpisodeReleasedForRating\(episode, seasonAirDate/);
assert.match(details, /data-action="episode-rating-choice"/);
assert.doesNotMatch(details, /restoreEpisodeAggregate|saveManualRating|series_episode_catalog_manual|series_episode_modal_aggregate/);
assert.doesNotMatch(details + detailsHtml, /seriesEpisodeRatingSummary|season-card__episode-average/);
assert.match(details, /handleSeasonsBrowserKeydown/);
assert.match(details, /ArrowLeft/);
assert.match(details, /ArrowRight/);
assert.match(details, /Home/);
assert.match(details, /End/);
assert.doesNotMatch(detailsHtml, /seriesAggregateRatingNotice|deleteSeriesRatingBtn|restoreSeriesAggregateBtn|enterManualSeriesRatingBtn/);
assert.match(detailsCss, /:focus-visible/);
assert.match(detailsCss, /#ratingModal \[hidden\]/);
assert.match(read('src/shared/styles/ratings.css'), /#ratingModal \[hidden\]\s*\{\s*display: none !important/);
assert.match(detailsCss, /\.episode-play-btn\.is-resume,[\s\S]*?\.episode-play-btn\.is-playing\s*\{[^}]*color: var\(--ui-color-page\)/);
assert.match(details, /role="radiogroup"/);
assert.match(details, /role="radio"/);
assert.match(details, /aria-checked=/);
assert.match(details, /getSeasonEpisodeChartStats/);
assert.match(details, /getEpisodeChartHeight/);
assert.match(details, /getDefaultSeasonEpisode/);
assert.match(details, /navigateSeasonEpisode/);
assert.match(details, /loadSelectedSeason/);
assert.doesNotMatch(details, /toggleEpisodeRatingPopover|closeEpisodeRatingPopovers|toggleSeasonEpisodes/);
const refresh = details.slice(details.indexOf('    async refreshSeasonsProgress('), details.indexOf('    initSelectionPopup('));
assert.match(refresh, /updateSeasonsBrowserState/);
assert.doesNotMatch(refresh, /tabPane\.innerHTML\s*=/, 'progress refresh does not replace the seasons block');
assert.match(tmdb, /tmdbEpisodeId: Number\.isInteger\(Number\(rawEp\.id\)\)/);
assert.doesNotMatch(ratings, /episodeAverage|episodesRatedCount|saveManualRating|series_episode_edit_notice/);
assert.doesNotMatch(card, /myEpisodesRatedCount|userRatingDisplay|mc-badge-user-caption/);
assert.match(details, /episode-user-rating-badge/);
assert.match(read('src/shared/i18n/locales.js'), /personal_rating: "Ваша оценка: \{rating\}\/10"/);

console.log('seriesEpisodeRatingsContract.test.cjs: all tests passed');
